"""remove agent fields from enquiry

Revision ID: 151a315e654e
Revises: d2e3f4a5b6c7
Create Date: 2026-04-20 17:30:39.835875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '151a315e654e'
down_revision: Union[str, None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enquiries', sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('enquiries', 'client_verification_status')
    op.drop_column('enquiries', 'agent_state')
    op.drop_column('enquiries', 'client_is_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('client_is_new', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('enquiries', sa.Column('agent_state', sa.JSON(), autoincrement=False, nullable=True))
    op.add_column('enquiries', sa.Column('client_verification_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('enquiries', 'processing_completed_at')
    op.drop_column('enquiries', 'processing_started_at')
    # ### end Alembic commands ###
