/** Mirror backend `config/permissions.py` values for UI checks. */
export const Permissions = {
  UPLOAD_EMAIL: 'upload_email',
  VIEW_ENQUIRIES: 'view_enquiries',
  DELETE_ENQUIRIES: 'delete_enquiries',
  EXPORT_ENQUIRIES: 'export_enquiries',
  VIEW_QUOTATIONS: 'view_quotations',
  APPROVE_QUOTATIONS: 'approve_quotations',
  DELETE_QUOTATIONS: 'delete_quotations',
  DOWNLOAD_PDF: 'download_pdf',
  HITL_APPROVE: 'hitl_approve',
  HITL_EDIT_EMAIL: 'hitl_edit_email',
  HITL_CUSTOM_PROMPT: 'hitl_custom_prompt',
  CLIENT_VERIFY: 'client_verify',
  CLIENT_VIEW: 'client_view',
  ERP_EXPORT: 'erp_export',
  ERP_DOWNLOAD: 'erp_download',
  MASTERS_VIEW: 'masters_view',
  MASTERS_EDIT: 'masters_edit',
  MASTERS_UPLOAD_PRICELIST: 'masters_upload_pricelist',
  EMAIL_SYNC_VIEW: 'email_sync_view',
  EMAIL_SYNC_TRIGGER: 'email_sync_trigger',
  REPORTS_VIEW: 'reports_view',
  REPORTS_EXPORT: 'reports_export',
  USERS_VIEW: 'users_view',
  USERS_CREATE: 'users_create',
  USERS_EDIT: 'users_edit',
  USERS_DEACTIVATE: 'users_deactivate',
  SYSTEM_SETTINGS_VIEW: 'system_settings_view',
  SYSTEM_SETTINGS_EDIT: 'system_settings_edit',
  AUDIT_LOG_VIEW: 'audit_log_view',
} as const

export type PermissionValue = (typeof Permissions)[keyof typeof Permissions]
